title = "祷告手册"
author = "作者：不详"
description = "耶和华阿，求你留心听我的祷告，垂听我恳求的声音 [诗 86:6]"

[ebook]
version = "1.0"
creator = "大卫"
subject = "基督教"
sources = "*.md"
format = ["epub"]
output = "../../ebooks/"
#qrcode = true
